// Generated by CoffeeScript 1.6.3
(function() {
  var checkAuth, checkExtensionWorking, config, createPopup, incorrectWindow, init, initEvents, unAuthorized, _sendMessageToActiveTab;

  config = require('../common.js').config;

  _sendMessageToActiveTab = function(msg, callback) {
    return chrome.tabs.query({
      active: true,
      currentWindow: true
    }, function(tabs) {
      return chrome.tabs.sendMessage(tabs[0].id, msg, callback);
    });
  };

  init = function() {
    var app;
    app = {};
    app.service = analytics.getService('chrome_extension');
    app.tracker = app.service.getTracker('UA-54177324-2');
    app.tracker.sendAppView('Popup');
    return checkExtensionWorking(app);
  };

  checkExtensionWorking = function(app) {
    return _sendMessageToActiveTab({
      statusChecking: true
    }, function(response) {
      if (response) {
        if (response.isWorking) {
          return checkAuth(app);
        } else {
          return unAuthorized(app);
        }
      } else {
        return incorrectWindow(app);
      }
    });
  };

  checkAuth = function(app) {
    return chrome.runtime.sendMessage({
      backendName: "authBackend",
      method: 'checkAuth'
    }, function(response) {
      if (response.user != null) {
        app.tracker.sendEvent('Popup', 'Popup opened successfully', '');
        app.user = response.user;
        return createPopup(app);
      } else {
        return unAuthorized(app);
      }
    });
  };

  initEvents = function(app) {
    $('body').on('click', 'a', function() {
      app.tracker.sendEvent('Popup', 'Link was opened from popup', "linkText:'" + ($(this).text()) + "', linkUrl:" + ($(this).attr('href')));
      chrome.tabs.create({
        url: $(this).attr('href')
      });
      return false;
    });
    return $('.js-create-todo-btn').on('click', function() {
      var postUrl, xhr;
      app.tracker.sendEvent('Popup', 'Create todo btn', "");
      postUrl = "" + config.site.url + "/todos/";
      xhr = new XMLHttpRequest();
      xhr.open('PUT', postUrl, true);
      xhr.send();
      return _sendMessageToActiveTab({
        'refresh': "newTodo"
      });
    });
  };

  createPopup = function(app) {
    initEvents(app);
    return $('#display-name').text(app.user.displayName);
  };

  unAuthorized = function(app) {
    app.tracker.sendEvent('Error in extension', 'Popup opened by anonymous', '');
    $('#anonymous-content').show();
    return $('#authorized-content').hide();
  };

  incorrectWindow = function(app) {
    app.tracker.sendEvent('Error in extension', 'Popup in incorrect page', '');
    $('#incorrect-window-content').show();
    return $('#authorized-content').hide();
  };

  init();

}).call(this);

/*
//@ sourceMappingURL=popup.map
*/
