// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(response) {
    if (response.resource instanceof Array && !response.resource.length) {
      chrome.runtime.sendMessage({
        backendName: "notificationBackend",
        method: 'create',
        params: {
          type: "basic",
          title: "У вас нет созданных дел",
          message: "Нажмите на иконку расширения и кликните \"Создать новое дело\"",
          iconUrl: "img/128x128.png",
          notificationName: "emptyTodolistNotification"
        }
      }, function(response) {});
    }
    return response;
  };

}).call(this);

/*
//@ sourceMappingURL=emptyTodolist.map
*/
