// Generated by CoffeeScript 1.6.3
(function() {
  var Notification;

  Notification = require('../../utils/notification');

  module.exports = function(response) {
    var notification;
    if (response.resource instanceof Array) {
      response.resource.forEach(function(todo) {
        var notification;
        notification = new Notification();
        return todo.notifier = function() {
          return notification;
        };
      });
    } else {
      notification = new Notification();
      response.resource.notifier = function() {
        return notification;
      };
    }
    return response.resource;
  };

}).call(this);

/*
//@ sourceMappingURL=notification.map
*/
