// Generated by CoffeeScript 1.6.3
(function() {
  exports.get = function(req, res, next) {
    if (!req.user) {
      return res.redirect('/');
    }
    return res.render('cabinet');
  };

}).call(this);

/*
//@ sourceMappingURL=cabinet.map
*/
