// Generated by CoffeeScript 1.6.3
(function() {
  var url;

  url = require('url');

  exports.get = function(req, res, next) {
    var query;
    query = url.parse(req.url, true).query;
    if (req.user && !("no_redirect" in query)) {
      return res.redirect('/cabinet');
    } else {
      return res.render('frontpage');
    }
  };

}).call(this);

/*
//@ sourceMappingURL=frontpage.map
*/
