// Generated by CoffeeScript 1.6.3
(function() {
  module.exports.config = {
    site: {
      url: "http://vspomni-delo.ru",
      title: "Вспомни дело"
    },
    vk: {
      id: "4412700"
    }
  };

  module.exports.config = {
    site: {
      url: "http://localhost:3000",
      title: "Вспомни дело"
    },
    vk: {
      id: "4412700"
    }
  };

}).call(this);

/*
//@ sourceMappingURL=common.map
*/
