// Generated by CoffeeScript 1.6.3
(function() {
  var config, env, getLogger, winston;

  winston = require('winston');

  config = require('config/index');

  env = config.get('env');

  getLogger = function(module) {
    var logger, path;
    path = module.filename.split('/').slice(-2).join('/');
    logger = new winston.Logger({
      transports: [
        new winston.transports.Console({
          colorize: true,
          level: env === 'development' ? 'debug' : 'error',
          label: path
        })
      ]
    });
    if (env === 'production') {
      logger.add(winston.transports.File, {
        filename: 'logs/debug.log',
        handleExceptions: true,
        level: 'debug',
        label: path
      });
    }
    return logger;
  };

  module.exports = getLogger;

}).call(this);

/*
//@ sourceMappingURL=log.map
*/
