// Generated by CoffeeScript 1.6.3
(function() {
  var config, mongoose;

  mongoose = require('mongoose');

  config = require('config');

  mongoose.connect(config.get('mongoose:uri'), config.get('mongoose:options'));

  module.exports = mongoose;

}).call(this);

/*
//@ sourceMappingURL=mongoose.map
*/
