// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty;

  module.exports = function(request, response, templateName, context) {
    var full_context, prop;
    if (context == null) {
      context = {};
    }
    full_context = {};
    for (prop in context) {
      if (!__hasProp.call(context, prop)) continue;
      full_context[prop] = context[prop];
    }
    return response.render(templateName, full_context);
  };

}).call(this);

/*
//@ sourceMappingURL=render.map
*/
