// Generated by CoffeeScript 1.6.3
(function() {
  var HttpError, http, https;

  http = require("http");

  https = require("https");

  HttpError = require('error/index').HttpError;

  exports.getJSON = function(options, onResult) {
    var prot, req, _ref;
    prot = (_ref = options.port === 443) != null ? _ref : {
      https: http
    };
    req = https.request(options, function(res) {
      var output;
      output = '';
      console.log(options.host + ':' + res.statusCode);
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return output += chunk;
      });
      return res.on('end', function() {
        var obj;
        obj = JSON.parse(output);
        return onResult(res.statusCode, obj);
      });
    });
    req.on('error', function(err) {
      throw new HttpError("Error while request: " + err);
    });
    return req.end();
  };

}).call(this);

/*
//@ sourceMappingURL=request.map
*/
