// Generated by CoffeeScript 1.6.3
(function() {
  var MongoStore, expressSession, mongoose;

  mongoose = require('utils/mongoose');

  expressSession = require('express-session');

  MongoStore = require('connect-mongo')(expressSession);

  module.exports = new MongoStore({
    mongoose_connection: mongoose.connection
  });

}).call(this);

/*
//@ sourceMappingURL=sessionStore.map
*/
