// Generated by CoffeeScript 1.6.3
(function() {
  exports.get = function(req, res, next) {
    if (req.user) {
      return res.json(req.user);
    } else {
      return res.json(403, {
        status: "error",
        err: "User is anonymous"
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=get-user.map
*/
