// Generated by CoffeeScript 1.6.3
(function() {
  exports.get = function(req, res, next) {
    req.logout();
    return res.redirect('/');
  };

}).call(this);

/*
//@ sourceMappingURL=logout.map
*/
