// Generated by CoffeeScript 1.6.3
(function() {
  var HttpError, config, errorhandler, express, log;

  express = require('express');

  log = require('utils/log')(module);

  HttpError = require('error/index').HttpError;

  config = require('config/index');

  errorhandler = require('errorhandler')();

  module.exports = function(err, req, res, next) {
    if (typeof err === 'number') {
      err = new HttpError(err);
    }
    if (err instanceof HttpError) {
      return res.sendHttpError(err);
    } else {
      if (config.get('env') === 'development') {
        return errorhandler(err, req, res, next);
      } else {
        log.error(err.message);
        err = new HttpError(500);
        return res.sendHttpError(err);
      }
    }
  };

}).call(this);

/*
//@ sourceMappingURL=errorHandler.map
*/
