// Generated by CoffeeScript 1.6.3
(function() {
  var HttpError, http, path,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  path = require('path');

  http = require('http');

  HttpError = (function(_super) {
    __extends(HttpError, _super);

    function HttpError(status, message) {
      this.status = status;
      this.message = message != null ? message : http.STATUS_CODES[status] || "Error";
      Error.apply(this, arguments);
      Error.captureStackTrace(this, HttpError);
    }

    return HttpError;

  })(Error);

  exports.HttpError = HttpError;

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
