// Generated by CoffeeScript 1.6.3
(function() {
  var AuthBackend, BaseBackend, NotificationBackend, config,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  config = require('../common.js').config;

  BaseBackend = require('./baseBackend.js');

  NotificationBackend = require('./notificationBackend.js');

  AuthBackend = (function(_super) {
    __extends(AuthBackend, _super);

    function AuthBackend(app) {
      this.app = app;
      this.checkAuth = __bind(this.checkAuth, this);
      this._notificationBackend = new NotificationBackend();
    }

    AuthBackend.prototype.getCookie = function(request, sendResponse) {
      chrome.cookies.get({
        url: config.site.url,
        name: "sid"
      }, function(cookie) {
        return sendResponse({
          cookie: cookie
        });
      });
      return true;
    };

    AuthBackend.prototype.checkAuth = function(request, sendResponse) {
      var _this = this;
      this.connect({
        url: "" + config.site.url + "/api/users/current",
        callback: function(err, response) {
          if (err) {
            _this._notificationBackend.create({
              params: {
                type: "basic",
                title: "Вспомни Дело — вы не авторизованы",
                message: "Нажмите на иконку расширения и авторизуйтесь",
                iconUrl: "img/128x128.png",
                notificationName: "anonimousNotification"
              }
            });
            return sendResponse({
              user: null
            });
          }
          return sendResponse({
            user: response
          });
        }
      });
      return true;
    };

    return AuthBackend;

  })(BaseBackend);

  module.exports = AuthBackend;

}).call(this);

/*
//@ sourceMappingURL=authBackend.map
*/
