// Generated by CoffeeScript 1.6.3
(function() {
  var BaseBackend, EmitterBackend, config,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  config = require('../common.js').config;

  BaseBackend = require('./baseBackend.js');

  EmitterBackend = (function(_super) {
    __extends(EmitterBackend, _super);

    function EmitterBackend(app) {
      this.app = app;
    }

    EmitterBackend.prototype.createTodo = function(request, sendResponse) {
      this.connect({
        url: "" + config.site.url + "/todos/",
        method: "PUT"
      });
      return true;
    };

    EmitterBackend.prototype.getTemplateForAnonymous = function(request, sendResponse) {
      var templateForAnonymous;
      templateForAnonymous = document.getElementById('anonymous-template');
      return sendResponse({
        template: templateForAnonymous.innerHTML
      });
    };

    return EmitterBackend;

  })(BaseBackend);

  module.exports = EmitterBackend;

}).call(this);

/*
//@ sourceMappingURL=emitterBackend.map
*/
