// Generated by CoffeeScript 1.6.3
(function() {
  var BaseBackend, TemplateBackend,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseBackend = require('./baseBackend.js');

  TemplateBackend = (function(_super) {
    __extends(TemplateBackend, _super);

    function TemplateBackend(app) {
      this.app = app;
    }

    TemplateBackend.prototype.getFrameTemplate = function(request, sendResponse) {
      var frameTemplate;
      frameTemplate = document.getElementById('frame-template');
      return sendResponse({
        template: frameTemplate.innerHTML
      });
    };

    TemplateBackend.prototype.getTemplateForAnonymous = function(request, sendResponse) {
      var templateForAnonymous;
      templateForAnonymous = document.getElementById('anonymous-template');
      return sendResponse({
        template: templateForAnonymous.innerHTML
      });
    };

    return TemplateBackend;

  })(BaseBackend);

  module.exports = TemplateBackend;

}).call(this);

/*
//@ sourceMappingURL=templateBackend.map
*/
