// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('saveOnBlurDirective', []).directive('saveOnBlur', [
    function() {
      return {
        restrict: 'A',
        require: 'ngModel',
        link: function(scope, element, attrs) {
          return element.on('blur', function($event) {
            return scope.updateTodo(scope.todo);
          });
        }
      };
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=saveOnBlur.map
*/
